### ISSUE TITLE
capgo.app/onboarding/verify_email does not work

### ISSUE THREAD

**Issue by iBobik** [Cap-go/capgo-cli#1]
`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'n.hash')`

In Firefox and Safari and is stuck on spinner.

However e-mail was verified, so it is possible to login from homepage and continue.

**Comment by riderx** [comment]
@iBobik thanks for the feedback, and sorry for the delayed response, i didn't check much the repo of the CLI
it was fixed  4 days ago !
