### ISSUE TITLE
Delete via CLI or API gives an error 400 "You can't edit this app" 

### ISSUE THREAD

**Issue by Dwimcore** [Cap-go/capgo-cli#15]
Hello, 

First of all, thank you for your work !

I have an issue with the cli that gives me an error "You can't edit this app" when I try to delete an app version, using : 
```
yarn capgo delete my.app.id -v 0.0.x --apikey=xxx (all API key)
```
I then tried using a request on your REST API and it gives me the same result : 
```
400 BAD REQUEST

{
	"status": "You can't edit this app"
}
```

Am I doing something wrong ?

Thanks in advance for your response and have a nice day :)

**Comment by riderx** [comment]
@Dwimcore do the API key are the one from the user who created the app on the cloud ?

can you send me in DM in discord your email i can check it

**Comment by riderx** [comment]
@Dwimcore i think this is fixed can you try it now ?

**Comment by Dwimcore** [comment]
@riderx Yes it seems so, thank you !
