### ISSUE TITLE
Changelog doesn't reflect what actually changed

### ISSUE THREAD

**Issue by arendjantetteroo** [Cap-go/capgo-cli#24]
https://github.com/Cap-go/capgo-cli/blob/main/CHANGELOG.md

With the feature for #17 merged, i would have expected it to show up somehow in the changelog.

**Comment by riderx** [comment]
Oh your are right, your commit didn’t follow the convention https://www.conventionalcommits.org/en/v1.0.0/ so they didn’t generate change :/ I should have told you
